services:
  portainer:
    container_name: Portainer
    image: portainer/portainer-ce
    platform: linux/amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock

volumes:
  data:
