services:
  chromadb:
    container_name: ChromaDB
    image: chromadb/chroma
    volumes:
      - chroma:/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "</dev/tcp/localhost/8000"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
